from treino_recursividade import soma_recursiva
from treino_recursividade import potencia_recursiva
from treino_recursividade import fibonacci
from treino_recursividade import numeros_pares
from treino_recursividade import contagem_de_ocorrencias
from treino_recursividade import soma_elementos_lista
from treino_recursividade import fatorial

print(fatorial(5))